# ==============================================================================
# netlify.yml
# ------------------------------------------------------------------------------
#
# Deployment config for https://www.netlify.com/
# You will also need to add a `netlify.toml` file with the following:
#
# [build]
#
# publish = "site"
# command = "npm --prefix themes/default/ run build:netlify"
#
# NODE_VERSION = "14.17.5"
#
# HUGO_VERSION = "0.82.1"
# HUGO_ENV = "production"
# HUGO_ENABLEGITINFO = "true"
#
# GIT_LFS_ENABLED = "true"
# GIT_LFS_FETCH_INCLUDE = "*.jpeg,*.jpg,*.png,*.gif,*.epub,*.mobi,*.pdf,*.html"
#

baseURL: "/"
relativeURLs: true

params:
  runTests: false
